### ISSUE TITLE
Add ability to daemonize sstpd

### ISSUE THREAD

**Issue by deba12** [sorz/sstp-server#12]
it will be very useful if you add knob for daemonize the daemon :)
using screen is some how quirky

**Comment by sorz** [comment]
You may use systemd or supervisor.

I prefer systemd, just create a `sstpd.service` file located in `/etc/systemd/system`
```
[Unit]
Description=SSTP server daemon.

[Service]
Type=simple
ExecStart=/usr/local/bin/sstpd -c ...
```
then,
```
# systemctl enable sstpd
# systemctl start sstpd
```
and view the log
```
$ journalctl -u sstpd
```

**Comment by deba12** [comment]
I will try it
thanks
