### ISSUE TITLE
Support for PROXY PROTOCOL

### ISSUE THREAD

**Issue by deba12** [sorz/sstp-server#15]
In my quest to place nginx infront of sstpd 
i found one huge limitation: can't get user ip address due to proxy.
Please add support (with configuration switch) 
for PROXY PROTOCOL 
http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt
I am not sure which version nginx supports so please add both of them.

**Comment by sorz** [comment]
Support PROXY PROTOCOL under `no-ssl` mode should be easy.
But I don't how to implement it over TLS yet.

**Comment by deba12** [comment]
Implement it with no-ssl and mention it in the readme :)
It have to work with nginx.

**Comment by sorz** [comment]
BTW, nginx/1.11.8 use PP1.
PP2 was tested with haproxy.

**Comment by deba12** [comment]
Great to hear it :)
I will try it later today

Thanks
