### ISSUE TITLE
mac下，怎么运行客户端？

### ISSUE THREAD

**Issue by luckypoem** [sorz/sstp-server#25]
有gui程序吗？还是用命令行？
如果用命令行，该怎么写？

tks

**Comment by sorz** [comment]
这是服务器，没有客户端。

**Comment by luckypoem** [comment]
在linux vps上，我运行了pip install sstp-server，安装了sstp-server。
我在mac上，也运行了pip install sstp-server，安装了sstp-server。

如何让mac上的sstp-server连接linux vps上的sstp-server？（从而让mac翻墙）
谢谢回复。

**Comment by sorz** [comment]
sstp-server 无法作为客户端连接另一台 sstp-server，你需要找一个 Mac 上能用的 SSTP 客户端。

**Comment by lingji** [comment]
可否使用win10 自带的sstp 做为客户端连接此sstp-server ？？

**Comment by sorz** [comment]
可以

**Comment by luckypoem** [comment]
@sorz 能否推荐一个 Mac 上能用的 SSTP 客户端程序？
